---
title: "STA304A1"
author: "Qizheng Wang"
date: "2020/2/6"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1
### Question 1 (a)
$\mu=\frac{1}{N}\sum_{i=1}^{N}y(e_i)=\frac{1}{4}*(3+1+0+5)=2.25$\newline
$\sigma_y^2=\frac{1}{4}*((4-2.25)^2+(3-2.25)^2+(0-2.25^2)+(5-2.25)^2)=\frac{65}{16}$\newline

### Question 1 (b)
#### (i) 
The number of possible SRSs of size n=2 is $\binom{4}{2}=6$\newline
Possible sample is 12,13,14,23,24,34(by label).\newline
For each sample,the probability that being selected is $\frac{1}{6}$.

#### (ii)
For $y_1=3,y_2=1$:$\bar{y}=\frac{1}{2}*(3+1)=2$,$s^2=\frac{1}{2-1}((3-2)^2+(1-2)^2)=2$\newline
For $y_1=3,y_3=0$:$\bar{y}=\frac{1}{2}*(3+0)=1.5$,$s^2=\frac{1}{2-1}((3-1.5)^2+(0-1.5)^2)=4.5$\newline
For $y_1=3,y_4=5$:$\bar{y}=\frac{1}{2}*(3+5)=4$,$s^2=\frac{1}{2-1}((3-4)^2+(5-4)^2)=2$\newline
For $y_2=1,y_3=0$:$\bar{y}=\frac{1}{2}*(1+0)=0.5$,$s^2=\frac{1}{2-1}((1-0.5)^2+(0-0.5)^2)=0.5$\newline
For $y_2=1,y_4=5$:$\bar{y}=\frac{1}{2}*(1+5)=3$,$s^2=\frac{1}{2-1}((1-3)^2+(5-3)^2)=8$\newline
For $y_3=0,y_4=5$:$\bar{y}=\frac{1}{2}*(0+5)=2.5$,$s^2=\frac{1}{2-1}((0-2.5)^2+(5-2.5)^2)=12.5$\newline


#### (iii)
$E(\bar{y})=\frac{2+1.5+4+0.5+3+2.5}{6}=2.25$\newline
$Var(\bar{y})=\frac{1}{6^2}*(2+4.5+2+0.5+8+12.5)=0.82$\newline
$\mu=\frac{3+1+0+5}{4}=\frac{9}{4}=2.25$\newline
$E(\bar{y})=\mu$\newline
Thus $\bar{y}$ is unbiased estimator of $\bar{Y}$, \newline
$Bias(\bar{y})=0$\newline
$MSE(\bar{y})=V(\bar{y})+[Bias(\bar{y})]^2=V(\bar{y})=0.82$

#### (iv)
$E(s^2)=\frac{2+4.5+2+0.5+8+12.5}{6}=\frac{29.5}{6}=4.916667$\newline
$V(s^2)=\frac{(2-4.92)^2+(4.5-4.92)^2+(2-4.92)^2+(0.5-4.92)^2+(8-4.92)^2+(12.5-4.92)^2}{6}=17.23$\newline

#### (v)
$\sigma^2=\frac{\sum_{i=1}^{N}(y_i-\mu)^2}{N}=\frac{(2-2.25)^2+(1.5-2.25)^2+(4-2.25)^2+(0.5-2.25)^2+(3-2.25)^2+(2.5-2.25)^2}{6}=3.48$\newline
Thus $\bar{y}$ is unbiased estimators for $\mu$, but $s^2$ is not unbiased for $\sigma^2$\newline

### Question 1(c)
#### (i)
The total number of possible SRSs of size n=2 is 16
The possible sample by label is 11,12,13,14,22,23,24,33,34,44.
Probability for 11,22,33,44 is $\frac{1}{16}$,probability for 12,13,14,23,24,34 is $\frac{1}{8}$

#### (ii)
For $y_1=3,y_1=3$:$\bar{y}=\frac{1}{2}*(3+3)=3$,$s^2=\frac{1}{3-3}((3-3)^2+(3-3)^2)=0$\newline
For $y_1=3,y_2=1$:$\bar{y}=\frac{1}{2}*(3+1)=2$,$s^2=\frac{1}{2-1}((3-2)^2+(1-2)^2)=2$\newline
For $y_1=3,y_3=0$:$\bar{y}=\frac{1}{2}*(3+0)=1.5$,$s^2=\frac{1}{2-1}((3-1.5)^2+(0-1.5)^2)=4.5$\newline
For $y_1=3,y_4=5$:$\bar{y}=\frac{1}{2}*(3+5)=4$,$s^2=\frac{1}{2-1}((3-4)^2+(5-4)^2)=2$\newline
Fpr $y_2=1,y_2=1$:$\bar{y}=\frac{1}{2}*(1+1)=1$,$s^2=\frac{1}{2-1}((1-1)^2+(1-1)^2)=0$\newline
For $y_2=1,y_3=0$:$\bar{y}=\frac{1}{2}*(1+0)=0.5$,$s^2=\frac{1}{2-1}((1-0.5)^2+(0-0.5)^2)=0.5$\newline
For $y_2=1,y_4=5$:$\bar{y}=\frac{1}{2}*(1+5)=3$,$s^2=\frac{1}{2-1}((1-3)^2+(5-3)^2)=8$\newline
For $y_3=0,y_3=0$:$\bar{y}=\frac{1}{2}*(0+0)=0$,$s^2=\frac{1}{2-1}((0-0)^2+(0-0)^2)=0$\newline
For $y_3=0,y_4=5$:$\bar{y}=\frac{1}{2}*(0+5)=2.5$,$s^2=\frac{1}{2-1}((0-2.5)^2+(5-2.5)^2)=12.5$\newline
For $y_4=5,y_4=5$:$\bar{y}=\frac{1}{2}*(5+5)=5$,$s^2=\frac{1}{2-1}((5-5)^2+(5-5)^2)=0$\newline

### (iii)
$E(\bar{y})=\frac{2*2+1.5*2+4*2+0.5*2+3*2+2.5*2+0*4}{16}=1.6875$\newline
$\mu=\frac{3+1+0+5}{4}=\frac{9}{4}=2.25$\newline
$E(\bar{y})=\mu+Bias(\bar{y})$=2.25-0.5625\newline
Thus $Bias(\bar{y})=-0.5625$\newline
$Var(\bar{y})=\frac{1}{16^2}*(0*4+2+2+4.5+4.5+2+2+0.5+0.5+8+8+12.5+12.5)=0.2305$\newline
$MSE(\bar{y})=V(\bar{y})+[Bias(\bar{y})]^2=0.2305-0.5625=-0.332$

#### (iv)
$E(s^2)=\frac{0*4+2+2+4.5+4.5+2+2+0.5+0.5+8+8+12.5+12.5}{16}=\frac{59}{16}=3.6875$\newline
$V(s^2)=\frac{(0-3.7)^2*4+(2-3.7)^2*4+(4.5-3.7)^2*2+(0.5-3.7)^2*2+(8-3.7)^2*2+(12.5-3.7)^2*2}{16}=14.93$\newline

#### (v)
$\sigma^2=\frac{\sum_{i=1}^{N}(y_i-\mu)^2}{N}=\frac{(0-2.25)^2*3+(2-2.25)^2*2+(1.5-2.25)^2*2+(4-2.25)^2*2+(0.5-2.25)^2*2+(3-2.25)^2*2+(2.5-2.25)^2*2}{16}=1.3554$\newline
Thus $Bias(\bar{y})=-0.5625$\newline
Thus $\bar{y}$ is biased estimator of $\mu$ \newline
And $s^2$ is not unbiased for $\sigma^2$\newline

### (d)
Sampling plan in b is better, because it is the unbiased estimator.
